import './globals.css';
import { Inter } from 'next/font/google';
import { ErzeugerProvider } from '@/context/erzeuger';
import { ImportDataProvider } from '@/context/importdata';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'babaproject',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ImportDataProvider>
          <ErzeugerProvider>{children}</ErzeugerProvider>
        </ImportDataProvider>
      </body>
    </html>
  );
}
